"""Detect whether the `ffmpeg` binary is installed on this system.

Docs: https://cj-mills.github.io/cjm-capability-ffmpegutils/availability.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/utils/availability.ipynb.

# %% auto #0
__all__ = ['FFMPEG_AVAILABLE']

# %% ../../nbs/utils/availability.ipynb #8fbacc93
import shutil
import logging

# Verify FFmpeg installation. True when the `ffmpeg` binary is on PATH.
FFMPEG_AVAILABLE = shutil.which("ffmpeg") is not None
if not FFMPEG_AVAILABLE:
    logging.warning(
        "FFmpeg not available - install the system package "
        "(e.g. apt install ffmpeg, brew install ffmpeg, or https://ffmpeg.org/)"
    )
