"""Metadata introspection for the FFmpeg media processing plugin used by `cjm-ctl` to generate the registration manifest.

Docs: https://cj-mills.github.io/cjm-media-plugin-ffmpegmeta.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/meta.ipynb.

# %% auto #0
__all__ = ['get_plugin_metadata']

# %% ../nbs/meta.ipynb #3e22e35e
import os
import sys
from typing import Any, Dict

from . import __version__

# %% ../nbs/meta.ipynb #3983c2e8
def get_plugin_metadata() -> Dict[str, Any]:  # Plugin metadata for manifest generation
    """Return metadata required to register this plugin with the PluginManager."""
    cjm_data_dir = os.environ.get("CJM_DATA_DIR")
    plugin_name = "cjm-media-plugin-ffmpeg"

    if cjm_data_dir:
        data_dir = os.path.join(cjm_data_dir, plugin_name)
    else:
        base_path = os.path.dirname(os.path.dirname(sys.executable))
        data_dir = os.path.join(base_path, "data")

    db_path = os.path.join(data_dir, "ffmpeg_jobs.db")
    os.makedirs(data_dir, exist_ok=True)

    return {
        "name": plugin_name,
        "version": __version__,
        "type": "media-processing",
        "category": "media",
        "interface": "cjm_media_plugin_system.processing_interface.MediaProcessingPlugin",
        "module": "cjm_media_plugin_ffmpeg.plugin",
        "class": "FFmpegProcessingPlugin",
        "python_path": sys.executable,
        "db_path": db_path,
        "resources": {
            "requires_gpu": False,
            "min_system_ram_mb": 512
        },
        "env_vars": {}
    }
