"""Probe media files for metadata (duration, ...) via ffprobe.

Docs: https://cj-mills.github.io/cjm-media-plugin-ffmpegutils/probe.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/utils/probe.ipynb.

# %% auto #0
__all__ = ['get_media_duration']

# %% ../../nbs/utils/probe.ipynb #365e8c58
from pathlib import Path
from typing import Optional
import subprocess

def get_media_duration(file_path: Path  # Path to the media file
                      ) -> Optional[float]:  # Duration in seconds, or None if it cannot be determined
    """Get the duration of a media file (seconds) via ffprobe."""
    duration_cmd = [
        'ffprobe',
        '-v', 'quiet',
        '-show_entries', 'format=duration',
        '-of', 'csv=p=0',
        str(file_path),
    ]
    try:
        duration_result = subprocess.run(
            duration_cmd, check=True, capture_output=True, text=True,
        )
        return float(duration_result.stdout.strip())
    except (subprocess.CalledProcessError, ValueError, FileNotFoundError):
        return None
